plugins {
    id 'java'
    id 'jacoco'
}

group = 'ru.nsu.aeliseev2.task212'
version = 'unspecified'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

javadoc {
    destinationDir = file("${rootDir}/build/docs/javadoc")
}

jacocoTestReport {
    reports {
        xml.required = true
        xml.outputLocation = layout.buildDirectory.file(
                "${rootDir}/build/reports/jacoco/test/jacocoTestReport.xml"
        )
    }
}